version: 2
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine

    steps:
      - checkout
      - restore_cache:
         keys:
           # Find a cache corresponding to this specific package-lock.json checksum
           # when this file is changed, this key will fail
           - v1-npm-deps-{{ checksum "package-lock.json" }}
           # Find the most recently generated cache used from any branch
           - v1-npm-deps-

      - run: npm install

      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run: npm run release-win

      - run: mkdir /tmp/circle-artifacts && cp release/*.zip /tmp/circle-artifacts
      - store_artifacts:
          path: /tmp/circle-artifacts

workflows:
  version: 2
  build:
    jobs:
      - build_windows
