version: 2
jobs:

  standard_version:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: git branch -u "origin/$CIRCLE_BRANCH" $CIRCLE_BRANCH
      - run: git config user.email "sdo@inbox.lv"
      - run: git config user.name "Dmitrijs Sadovskis"
      - run: git config push.default simple
      - run: npx standard-version
      - run: git push --follow-tags

  build_windows:
    docker:
      - image: electronuserland/builder:wine

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-

      - run: npm install

      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run: npm run release-win

      - run: mkdir circleci_workspace && mkdir circleci_workspace/artifacts && mkdir circleci_workspace/metadata
      - run: cp release/*.zip circleci_workspace/artifacts/
      - run: git describe --abbrev=0 --tags > circleci_workspace/metadata/version.txt

      - store_artifacts:
          path: circleci_workspace/artifacts

      - run: mkdir workspace
      - persist_to_workspace:
          root: circleci_workspace
          paths:
            - ./artifacts
            - ./metadata

  publish_github_release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./circleci_workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} $(cat ./circleci_workspace/metadata/version.txt) ./circleci_workspace/artifacts/

workflows:
  version: 2

  publish:
    jobs:
      - standard_version:
          filters:
            tags:
              ignore: /^v\d+\.\d+\.\d+$/

      - build_windows:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

      - publish_github_release:
          requires:
            - build_windows
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
